/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Order;
import Model.OrderDAO;
import Model.TextPrompt;
import java.text.DateFormat;

/**
 *
 * @author Randy
 */
public class AddOrderForm extends javax.swing.JFrame {
    
    DateFormat dateFormat = DateFormat.getDateInstance();
        
    OrderDAO orderDao = new OrderDAO();

    /**
     * Creates new form AddOrderForm
     */
    public AddOrderForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        TextPrompt orderNameHint = new TextPrompt("Enter a name", txtOrderName);
        TextPrompt motorcycleCodeHint = new TextPrompt("Enter the code", txtMotoCode);
        TextPrompt idHint = new TextPrompt("Order Id", txtIdOrder);
    }
    
    public void save(){
        String nameOrder = "";
        String currentDateOrder = "";
        String deliveryDateOrder = "";
        
       
        int  idOrder = 0;
        int  idMoto = 0;
        int  quantity = 0;
        idOrder= Integer.parseInt(txtIdOrder.getText());
        nameOrder= txtOrderName.getText();
       
        currentDateOrder = dateFormat.format(jDateNowOrder.getDate());
        deliveryDateOrder= dateFormat.format(jDateNowOrder.getDate());
        idMoto= Integer.parseInt(txtMotoCode.getText());
        quantity= (Integer)jsQuantity.getValue();
        Order order = new Order(idOrder,nameOrder,currentDateOrder,deliveryDateOrder,idMoto,quantity);
        orderDao.registerConcessioner(order);
          
    }
    
    public void clear(){
        txtIdOrder.setText("");
        txtOrderName.setText("");
        txtMotoCode.setText("");
        jDateNowOrder.setDate(null);
        jDateNowOrder.setDate(null);
        jsQuantity.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        TitleView = new javax.swing.JLabel();
        UnderlineTitleView = new javax.swing.JLabel();
        RegistryButton = new javax.swing.JLabel();
        CancelButton = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        txtIdOrder = new javax.swing.JTextField();
        txtOrderName = new javax.swing.JTextField();
        txtMotoCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateNowOrder = new com.toedter.calendar.JDateChooser();
        jDateDeliveryOrder = new com.toedter.calendar.JDateChooser();
        jsQuantity = new javax.swing.JSpinner();
        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        TitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Order Registry Text.png"))); // NOI18N
        TitleView.setAlignmentY(0.0F);
        jPnlBody.add(TitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 19, 220, 33));

        UnderlineTitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title View Underline.png"))); // NOI18N
        UnderlineTitleView.setAlignmentY(0.0F);
        jPnlBody.add(UnderlineTitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 540, 3));

        RegistryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Registry Button.png"))); // NOI18N
        RegistryButton.setAlignmentY(0.0F);
        RegistryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistryButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(RegistryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 435, 140, 35));

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel Button.png"))); // NOI18N
        CancelButton.setAlignmentY(0.0F);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 435, 140, 35));

        Id.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id.setForeground(new java.awt.Color(238, 112, 82));
        Id.setText("Date:");
        Id.setAlignmentY(0.0F);
        jPnlBody.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 131, 40, 19));

        Name.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(238, 112, 82));
        Name.setText("Id Order:");
        Name.setAlignmentY(0.0F);
        jPnlBody.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 131, 80, -1));

        Category.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Category.setForeground(new java.awt.Color(238, 112, 82));
        Category.setText("Order's Name:");
        Category.setAlignmentY(0.0F);
        jPnlBody.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 110, 19));

        Description.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Description.setForeground(new java.awt.Color(238, 112, 82));
        Description.setText("Delivery Date:");
        Description.setAlignmentY(0.0F);
        jPnlBody.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 246, 100, 19));

        Quantity.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Quantity.setForeground(new java.awt.Color(238, 112, 82));
        Quantity.setText("Motorcycle Code:");
        Quantity.setAlignmentY(0.0F);
        jPnlBody.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 308, 130, 19));

        Price.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Price.setForeground(new java.awt.Color(238, 112, 82));
        Price.setText("Quantity:");
        Price.setAlignmentY(0.0F);
        jPnlBody.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 367, 90, 19));

        txtIdOrder.setBackground(new java.awt.Color(255, 255, 255));
        txtIdOrder.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtIdOrder.setForeground(new java.awt.Color(36, 47, 65));
        txtIdOrder.setAlignmentX(0.0F);
        txtIdOrder.setAlignmentY(0.0F);
        txtIdOrder.setBorder(null);
        jPnlBody.add(txtIdOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 129, 194, 24));

        txtOrderName.setBackground(new java.awt.Color(255, 255, 255));
        txtOrderName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtOrderName.setForeground(new java.awt.Color(36, 47, 65));
        txtOrderName.setAlignmentX(0.0F);
        txtOrderName.setAlignmentY(0.0F);
        txtOrderName.setBorder(null);
        jPnlBody.add(txtOrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 188, 194, 24));

        txtMotoCode.setBackground(new java.awt.Color(255, 255, 255));
        txtMotoCode.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtMotoCode.setForeground(new java.awt.Color(36, 47, 65));
        txtMotoCode.setAlignmentX(0.0F);
        txtMotoCode.setAlignmentY(0.0F);
        txtMotoCode.setBorder(null);
        jPnlBody.add(txtMotoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 306, 172, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jPnlBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 153, 194, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jPnlBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 213, 194, 1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jPnlBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 194, 1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel5.setAlignmentY(0.0F);
        jPnlBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 194, 1));
        jPnlBody.add(jDateNowOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 127, -1, -1));
        jPnlBody.add(jDateDeliveryOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jsQuantity.setBorder(null);
        jsQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPnlBody.add(jsQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 190, -1));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new OrderModule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void RegistryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistryButtonMouseClicked
         if("".equals(txtIdOrder.getText()) || "".equals(txtOrderName.getText()) || "".equals(txtMotoCode.getText())
            || "".equals(jDateNowOrder.getDateFormatString()) || "".equals(jDateDeliveryOrder.getDateFormatString()))
        {
            OkDialog dialog = new OkDialog(this, true);
            dialog.dialogText.setText("All fields are required!");
            dialog.setVisible(true);
        }
        else
        {
            save();
            //limpiar();
        }

    }//GEN-LAST:event_RegistryButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        clear();
    }//GEN-LAST:event_CancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CancelButton;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel RegistryButton;
    private javax.swing.JLabel TitleView;
    private javax.swing.JLabel UnderlineTitleView;
    private com.toedter.calendar.JDateChooser jDateDeliveryOrder;
    private com.toedter.calendar.JDateChooser jDateNowOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JSpinner jsQuantity;
    private javax.swing.JTextField txtIdOrder;
    private javax.swing.JTextField txtMotoCode;
    private javax.swing.JTextField txtOrderName;
    // End of variables declaration//GEN-END:variables
}
