/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Randy
 */
public class Concessioner extends javax.swing.JFrame {

    /**
     * Creates new form Concessioner
     */
    public Concessioner() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        TitleView = new javax.swing.JLabel();
        AddConcessionerOption = new javax.swing.JLabel();
        EditConcessionerOption = new javax.swing.JLabel();
        ViewConcessionerOption = new javax.swing.JLabel();
        RemoveConcessionerOption = new javax.swing.JLabel();
        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        TitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Concessioner Text.png"))); // NOI18N
        TitleView.setAlignmentY(0.0F);
        jPnlBody.add(TitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 19, 230, 33));

        AddConcessionerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Add Concessioner.png"))); // NOI18N
        AddConcessionerOption.setAlignmentY(0.0F);
        AddConcessionerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddConcessionerOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(AddConcessionerOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 142, 163, 115));

        EditConcessionerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Edit Concessioner.png"))); // NOI18N
        EditConcessionerOption.setAlignmentY(0.0F);
        EditConcessionerOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditConcessionerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditConcessionerOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(EditConcessionerOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 139, 166, 118));

        ViewConcessionerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/View Concessioners.png"))); // NOI18N
        ViewConcessionerOption.setAlignmentY(0.0F);
        ViewConcessionerOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewConcessionerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewConcessionerOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(ViewConcessionerOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 302, 181, 151));

        RemoveConcessionerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Remove Concessioner.png"))); // NOI18N
        RemoveConcessionerOption.setAlignmentY(0.0F);
        RemoveConcessionerOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoveConcessionerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveConcessionerOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(RemoveConcessionerOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 336, 205, 117));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new MainAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void AddConcessionerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddConcessionerOptionMouseClicked
        new AddConcessionerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddConcessionerOptionMouseClicked

    private void EditConcessionerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditConcessionerOptionMouseClicked
        new ModifyConcessionerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditConcessionerOptionMouseClicked

    private void ViewConcessionerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewConcessionerOptionMouseClicked
        new ViewConcessionerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewConcessionerOptionMouseClicked

    private void RemoveConcessionerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveConcessionerOptionMouseClicked
        new DeleteConcessionerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RemoveConcessionerOptionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concessioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concessioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concessioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concessioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Concessioner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddConcessionerOption;
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel EditConcessionerOption;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel RemoveConcessionerOption;
    private javax.swing.JLabel TitleView;
    private javax.swing.JLabel ViewConcessionerOption;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    // End of variables declaration//GEN-END:variables
}
