/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.TextPrompt;

/**
 *
 * @author Randy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt userHint = new TextPrompt("Enter a username", txtUsername);
        TextPrompt passwordHint = new TextPrompt("Enter a password", txtPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();
        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        UserImage = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        UserUnderline = new javax.swing.JSeparator();
        PasswordUnderline = new javax.swing.JSeparator();
        btnEnter = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setAlignmentX(0.0F);
        jPnlBanner.setAlignmentY(0.0F);
        jPnlBanner.setName("jPnlBanner"); // NOI18N

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));

        javax.swing.GroupLayout jPnlBannerLayout = new javax.swing.GroupLayout(jPnlBanner);
        jPnlBanner.setLayout(jPnlBannerLayout);
        jPnlBannerLayout.setHorizontalGroup(
            jPnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlBannerLayout.setVerticalGroup(
            jPnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setAlignmentX(0.0F);
        jPnlWindowControls.setAlignmentY(0.0F);
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlWindowControlsLayout = new javax.swing.GroupLayout(jPnlWindowControls);
        jPnlWindowControls.setLayout(jPnlWindowControlsLayout);
        jPnlWindowControlsLayout.setHorizontalGroup(
            jPnlWindowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlWindowControlsLayout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .addComponent(MinimiceControl)
                .addGap(18, 18, 18)
                .addComponent(CloseControl)
                .addGap(22, 22, 22))
        );
        jPnlWindowControlsLayout.setVerticalGroup(
            jPnlWindowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlWindowControlsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPnlWindowControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinimiceControl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseControl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setAlignmentX(0.0F);
        jPnlBody.setAlignmentY(0.0F);
        jPnlBody.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPnlBody.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N

        UserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/User Image.png"))); // NOI18N
        UserImage.setAlignmentY(0.0F);
        UserImage.setPreferredSize(new java.awt.Dimension(123, 121));

        lblUser.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(238, 112, 82));
        lblUser.setText("User:");

        lblPassword.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(238, 112, 82));
        lblPassword.setText("Password:");

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/User Icon.png"))); // NOI18N

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Password Icon.png"))); // NOI18N

        UserUnderline.setForeground(new java.awt.Color(36, 47, 65));

        PasswordUnderline.setForeground(new java.awt.Color(36, 47, 65));

        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Enter Button.png"))); // NOI18N
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(36, 47, 65));
        txtUsername.setBorder(null);

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(36, 47, 65));
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);

        javax.swing.GroupLayout jPnlBodyLayout = new javax.swing.GroupLayout(jPnlBody);
        jPnlBody.setLayout(jPnlBodyLayout);
        jPnlBodyLayout.setHorizontalGroup(
            jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBodyLayout.createSequentialGroup()
                .addGroup(jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBodyLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(UserImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlBodyLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUser)
                            .addGroup(jPnlBodyLayout.createSequentialGroup()
                                .addComponent(UserIcon)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlBodyLayout.createSequentialGroup()
                                .addComponent(PasswordIcon)
                                .addGap(18, 18, 18)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UserUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlBodyLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnEnter)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPnlBodyLayout.setVerticalGroup(
            jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBodyLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(UserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlBodyLayout.createSequentialGroup()
                        .addGroup(jPnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserIcon)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblPassword)
                        .addGap(8, 8, 8)
                        .addComponent(PasswordIcon))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEnter)
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to exit?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
            System.exit(0);
    }//GEN-LAST:event_CloseControlMouseClicked

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        this.setVisible(false);
        MainAdmin form = new MainAdmin();
        form.setVisible(true);
        
        //Método para verificar tipo de usuario
        //Options.ValidateUserType(this.txtUsername.getText(), this.txtPassword.getText(), this);
        //Optiones es el nombre de la clase
    }//GEN-LAST:event_btnEnterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JSeparator PasswordUnderline;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserImage;
    private javax.swing.JSeparator UserUnderline;
    private javax.swing.JLabel btnEnter;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
