/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Randy
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBanner = new javax.swing.JPanel();
        WelcomeMessage = new javax.swing.JLabel();
        BackgroundBanner = new javax.swing.JLabel();
        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        OrdersOption = new javax.swing.JLabel();
        ConcessionerOption = new javax.swing.JLabel();
        WarehouseOption = new javax.swing.JLabel();
        UsersOption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setAlignmentX(0.0F);
        jPnlBanner.setAlignmentY(0.0F);
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Welcome Message.png"))); // NOI18N
        WelcomeMessage.setAlignmentY(0.0F);
        jPnlBanner.add(WelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 259, 294, 101));

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setAlignmentX(0.0F);
        jPnlWindowControls.setAlignmentY(0.0F);
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setAlignmentX(0.0F);
        jPnlBody.setAlignmentY(0.0F);
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrdersOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Orders.png"))); // NOI18N
        OrdersOption.setAlignmentY(0.0F);
        OrdersOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPnlBody.add(OrdersOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 76, 122, 181));

        ConcessionerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Concessioner.png"))); // NOI18N
        ConcessionerOption.setAlignmentY(0.0F);
        ConcessionerOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConcessionerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcessionerOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(ConcessionerOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 99, -1, 157));

        WarehouseOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Warehouse.png"))); // NOI18N
        WarehouseOption.setAlignmentY(0.0F);
        WarehouseOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WarehouseOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WarehouseOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(WarehouseOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 297, 140, 156));

        UsersOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Users.png"))); // NOI18N
        UsersOption.setAlignmentY(0.0F);
        UsersOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UsersOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersOptionMouseClicked(evt);
            }
        });
        jPnlBody.add(UsersOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 298, 139, 156));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void WarehouseOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarehouseOptionMouseClicked
        new Warehouse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WarehouseOptionMouseClicked

    private void ConcessionerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcessionerOptionMouseClicked
        new Concessioner().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConcessionerOptionMouseClicked

    private void UsersOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersOptionMouseClicked
        new UsersModule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsersOptionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel ConcessionerOption;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel OrdersOption;
    private javax.swing.JLabel UsersOption;
    private javax.swing.JLabel WarehouseOption;
    private javax.swing.JLabel WelcomeMessage;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    // End of variables declaration//GEN-END:variables
}
