/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ConcessionaireDAO;
import Model.ConcessionaireVO;

/**
 *
 * @author Melissa
 */
public class ModifyConcessionarieForm extends javax.swing.JFrame {
ConcessionaireDAO pieceDAO = new ConcessionaireDAO();
    ConcessionaireVO pieceVO;
    /**
     * Creates new form ModifyConcessionarieForm
     */
    public ModifyConcessionarieForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundBanner1 = new javax.swing.JLabel();
        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        UnderlineTitleView = new javax.swing.JLabel();
        RegistryButton = new javax.swing.JLabel();
        CancelButton = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        txtNombreConcesionario = new javax.swing.JTextField();
        txtRucConcesionario = new javax.swing.JTextField();
        txtCiudadConcesionario = new javax.swing.JTextField();
        txtTelefonoConcesionario = new javax.swing.JTextField();
        txtIdConcesionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionConcesionario = new javax.swing.JTextField();
        Price1 = new javax.swing.JLabel();
        txtRepresentanteConcesionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        txtCelularConcesionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailConcesionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFaxConcesionario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Id2 = new javax.swing.JLabel();
        Id3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundBanner1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner1.setAlignmentY(0.0F);
        BackgroundBanner1.setPreferredSize(new java.awt.Dimension(296, 577));

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        UnderlineTitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title View Underline.png"))); // NOI18N
        UnderlineTitleView.setAlignmentY(0.0F);
        jPnlBody.add(UnderlineTitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 540, 3));

        RegistryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Registry Button.png"))); // NOI18N
        RegistryButton.setAlignmentY(0.0F);
        RegistryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistryButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(RegistryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 140, 35));

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel Button.png"))); // NOI18N
        CancelButton.setAlignmentY(0.0F);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 35));

        Id.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id.setForeground(new java.awt.Color(238, 112, 82));
        Id.setText("Fax:");
        Id.setAlignmentY(0.0F);
        jPnlBody.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 80, 19));

        Name.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(238, 112, 82));
        Name.setText("Nombre:");
        Name.setAlignmentY(0.0F);
        jPnlBody.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 131, 80, -1));

        Category.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Category.setForeground(new java.awt.Color(238, 112, 82));
        Category.setText("Ruc:");
        Category.setAlignmentY(0.0F);
        jPnlBody.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 68, 19));

        Description.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Description.setForeground(new java.awt.Color(238, 112, 82));
        Description.setText("Dirección:");
        Description.setAlignmentY(0.0F);
        jPnlBody.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 246, 86, 19));

        Quantity.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Quantity.setForeground(new java.awt.Color(238, 112, 82));
        Quantity.setText("Ciudad");
        Quantity.setAlignmentY(0.0F);
        jPnlBody.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 308, 64, 19));

        Price.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Price.setForeground(new java.awt.Color(238, 112, 82));
        Price.setText("Telefono:");
        Price.setAlignmentY(0.0F);
        jPnlBody.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 19));

        txtNombreConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtNombreConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtNombreConcesionario.setAlignmentX(0.0F);
        txtNombreConcesionario.setAlignmentY(0.0F);
        txtNombreConcesionario.setBorder(null);
        jPnlBody.add(txtNombreConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 129, 194, 24));

        txtRucConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtRucConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtRucConcesionario.setAlignmentX(0.0F);
        txtRucConcesionario.setAlignmentY(0.0F);
        txtRucConcesionario.setBorder(null);
        jPnlBody.add(txtRucConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 188, 194, 24));

        txtCiudadConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtCiudadConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtCiudadConcesionario.setAlignmentX(0.0F);
        txtCiudadConcesionario.setAlignmentY(0.0F);
        txtCiudadConcesionario.setBorder(null);
        jPnlBody.add(txtCiudadConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 194, 24));

        txtTelefonoConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtTelefonoConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtTelefonoConcesionario.setAlignmentX(0.0F);
        txtTelefonoConcesionario.setAlignmentY(0.0F);
        txtTelefonoConcesionario.setBorder(null);
        jPnlBody.add(txtTelefonoConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 190, 24));

        txtIdConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtIdConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtIdConcesionario.setAlignmentX(0.0F);
        txtIdConcesionario.setAlignmentY(0.0F);
        txtIdConcesionario.setBorder(null);
        jPnlBody.add(txtIdConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 194, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jPnlBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 153, 194, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jPnlBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 213, 194, 1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel3.setAlignmentY(0.0F);
        jPnlBody.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 270, 194, 1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jPnlBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 330, 194, 1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel5.setAlignmentY(0.0F);
        jPnlBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 390, 194, 1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel6.setAlignmentY(0.0F);
        jPnlBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 20));

        txtDireccionConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtDireccionConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtDireccionConcesionario.setAlignmentX(0.0F);
        txtDireccionConcesionario.setAlignmentY(0.0F);
        txtDireccionConcesionario.setBorder(null);
        jPnlBody.add(txtDireccionConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 244, 194, 24));

        Price1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Price1.setForeground(new java.awt.Color(238, 112, 82));
        Price1.setText("Representante:");
        Price1.setAlignmentY(0.0F);
        jPnlBody.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 19));

        txtRepresentanteConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtRepresentanteConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtRepresentanteConcesionario.setAlignmentX(0.0F);
        txtRepresentanteConcesionario.setAlignmentY(0.0F);
        txtRepresentanteConcesionario.setBorder(null);
        jPnlBody.add(txtRepresentanteConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 365, 174, 24));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel7.setAlignmentY(0.0F);
        jPnlBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 440, 194, 10));

        Id1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id1.setForeground(new java.awt.Color(238, 112, 82));
        Id1.setText("Id a modificar:");
        Id1.setAlignmentY(0.0F);
        jPnlBody.add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, 19));

        txtCelularConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtCelularConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtCelularConcesionario.setAlignmentX(0.0F);
        txtCelularConcesionario.setAlignmentY(0.0F);
        txtCelularConcesionario.setBorder(null);
        jPnlBody.add(txtCelularConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 194, 24));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel8.setAlignmentY(0.0F);
        jPnlBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 250, 20));

        txtEmailConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtEmailConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtEmailConcesionario.setAlignmentX(0.0F);
        txtEmailConcesionario.setAlignmentY(0.0F);
        txtEmailConcesionario.setBorder(null);
        jPnlBody.add(txtEmailConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 194, 24));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel9.setAlignmentY(0.0F);
        jPnlBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 250, 20));

        txtFaxConcesionario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtFaxConcesionario.setForeground(new java.awt.Color(36, 47, 65));
        txtFaxConcesionario.setAlignmentX(0.0F);
        txtFaxConcesionario.setAlignmentY(0.0F);
        txtFaxConcesionario.setBorder(null);
        jPnlBody.add(txtFaxConcesionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 194, 24));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel10.setAlignmentY(0.0F);
        jPnlBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 250, 20));

        Id2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id2.setForeground(new java.awt.Color(238, 112, 82));
        Id2.setText("Celular:");
        Id2.setAlignmentY(0.0F);
        jPnlBody.add(Id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 80, 19));

        Id3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id3.setForeground(new java.awt.Color(238, 112, 82));
        Id3.setText("Email:");
        Id3.setAlignmentY(0.0F);
        jPnlBody.add(Id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlWindowControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlWindowControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new ConcessionaireMenu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BackControlMouseClicked

    private void RegistryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistryButtonMouseClicked
        if("".equals(txtNombreConcesionario.getText()) || "".equals(txtRucConcesionario.getText()) || "".equals(txtCiudadConcesionario.getText())
            || "".equals(txtCiudadConcesionario.getText()) || "".equals(txtTelefonoConcesionario.getText())
            || "".equals(txtCelularConcesionario.getText()) || "".equals(txtEmailConcesionario.getText())
            || "".equals(txtEmailConcesionario.getText()) || "".equals(txtFaxConcesionario.getText())
            || "".equals(txtFaxConcesionario.getText()) || "".equals(txtIdConcesionario.getText())
            || "".equals(txtIdConcesionario.getText()) || "".equals(txtRepresentanteConcesionario.getText())
            || "".equals(txtDireccionConcesionario.getText())
        )
        {
            OkDialog dialog = new OkDialog(this, true);
            dialog.dialogText.setText("All fields are required!");
            dialog.setVisible(true);
        }
        else
        {
            int id;
            String ruc, nombre, direccion, ciudad, representante, telefono, celular, email, fax;
            id=Integer.parseInt(this.txtIdConcesionario.getText());
            ruc=this.txtRucConcesionario.getText();
            nombre=this.txtNombreConcesionario.getText();
            direccion=this.txtDireccionConcesionario.getText();
            ciudad=this.txtCiudadConcesionario.getText();
            representante=this.txtRepresentanteConcesionario.getText();
            telefono=this.txtTelefonoConcesionario.getText();
            celular=this.txtCelularConcesionario.getText();
            email=this.txtEmailConcesionario.getText();
            fax=this.txtFaxConcesionario.getText();
            pieceVO=new ConcessionaireVO(id, ruc,nombre, direccion, ciudad, representante,  telefono, celular, email,fax);
            pieceDAO.modificarConcesionario(pieceVO);
            txtNombreConcesionario.setText("");
            txtRucConcesionario.setText("");
            txtCiudadConcesionario.setText("");
            this.txtCelularConcesionario.setText("");
            txtTelefonoConcesionario.setText("");
            this.txtEmailConcesionario.setText("");
            this.txtFaxConcesionario.setText("");
            this.txtIdConcesionario.setText("");
            this.txtRepresentanteConcesionario.setText("");
            this.txtDireccionConcesionario.setText("");
        }
    }//GEN-LAST:event_RegistryButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        txtNombreConcesionario.setText("");
        txtRucConcesionario.setText("");
        txtCiudadConcesionario.setText("");
        this.txtCelularConcesionario.setText("");
        txtTelefonoConcesionario.setText("");
        this.txtEmailConcesionario.setText("");
        this.txtFaxConcesionario.setText("");
        this.txtIdConcesionario.setText("");
        this.txtRepresentanteConcesionario.setText("");
        this.txtDireccionConcesionario.setText("");

    }//GEN-LAST:event_CancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionarieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionarieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionarieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionarieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyConcessionarieForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner1;
    private javax.swing.JLabel CancelButton;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel Id2;
    private javax.swing.JLabel Id3;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel RegistryButton;
    private javax.swing.JLabel UnderlineTitleView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JTextField txtCelularConcesionario;
    private javax.swing.JTextField txtCiudadConcesionario;
    private javax.swing.JTextField txtDireccionConcesionario;
    private javax.swing.JTextField txtEmailConcesionario;
    private javax.swing.JTextField txtFaxConcesionario;
    private javax.swing.JTextField txtIdConcesionario;
    private javax.swing.JTextField txtNombreConcesionario;
    private javax.swing.JTextField txtRepresentanteConcesionario;
    private javax.swing.JTextField txtRucConcesionario;
    private javax.swing.JTextField txtTelefonoConcesionario;
    // End of variables declaration//GEN-END:variables
}
