/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ConcessionerDAO;
import Model.ConcessionerVO;
import Model.TextPrompt;

/**
 *
 * @author Randy
 */
public class ModifyConcessionerForm extends javax.swing.JFrame {
    ConcessionerDAO concessionerDAO = new ConcessionerDAO();
    ConcessionerVO concessionerVO;
    /**
     * Creates new form ModifyConcessionerForm
     */
    public ModifyConcessionerForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        TextPrompt nameHint = new TextPrompt("Enter a name", txtConcessionerName);
        TextPrompt rucHint = new TextPrompt("Enter RUC", txtConcessionerRUC);
        TextPrompt cityHint = new TextPrompt("Enter the city", txtConcessionerCity);
        TextPrompt addressHint = new TextPrompt("Enter the address", txtConcessionerAddress);
        TextPrompt legalRepresentativeHint = new TextPrompt("Representant's Name", txtConcessionerLegalRepresentative);
        TextPrompt idHint = new TextPrompt("Enter the ID to change", txtConcessionerId);
        TextPrompt phoneHint = new TextPrompt("Enter a phone number", txtConcessionerPhone);
        TextPrompt cellphoneHint = new TextPrompt("Enter a cellphone number", txtConcessionerCellphone);
        TextPrompt emailHint = new TextPrompt("Enter a email", txtConcessionerEmail);
        TextPrompt faxHint = new TextPrompt("Enter a fax number", txtConcessionerFax);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        TitleView = new javax.swing.JLabel();
        UnderlineTitleView = new javax.swing.JLabel();
        SaveButton = new javax.swing.JLabel();
        CancelButton = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        RUC = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LegalRepresentative = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Cellphone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Fax = new javax.swing.JLabel();
        txtConcessionerName = new javax.swing.JTextField();
        txtConcessionerRUC = new javax.swing.JTextField();
        txtConcessionerCity = new javax.swing.JTextField();
        txtConcessionerAddress = new javax.swing.JTextField();
        txtConcessionerLegalRepresentative = new javax.swing.JTextField();
        txtConcessionerId = new javax.swing.JTextField();
        txtConcessionerPhone = new javax.swing.JTextField();
        txtConcessionerCellphone = new javax.swing.JTextField();
        txtConcessionerEmail = new javax.swing.JTextField();
        txtConcessionerFax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        TitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Edit Concessioner Text.png"))); // NOI18N
        TitleView.setAlignmentY(0.0F);
        jPnlBody.add(TitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 19, 320, 33));

        UnderlineTitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title View Underline.png"))); // NOI18N
        UnderlineTitleView.setAlignmentY(0.0F);
        jPnlBody.add(UnderlineTitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 540, 3));

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Save Button.png"))); // NOI18N
        SaveButton.setAlignmentY(0.0F);
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 435, 140, 35));

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel Button.png"))); // NOI18N
        CancelButton.setAlignmentY(0.0F);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        jPnlBody.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 435, 140, 35));

        Id1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id1.setForeground(new java.awt.Color(238, 112, 82));
        Id1.setText("Id:");
        Id1.setAlignmentY(0.0F);
        jPnlBody.add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 79, 18, 19));

        Name.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(238, 112, 82));
        Name.setText("Name:");
        Name.setAlignmentY(0.0F);
        jPnlBody.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 131, 46, -1));

        RUC.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        RUC.setForeground(new java.awt.Color(238, 112, 82));
        RUC.setText("RUC:");
        RUC.setAlignmentY(0.0F);
        jPnlBody.add(RUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 68, 19));

        City.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        City.setForeground(new java.awt.Color(238, 112, 82));
        City.setText("City:");
        City.setAlignmentY(0.0F);
        jPnlBody.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 246, 86, 19));

        Address.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Address.setForeground(new java.awt.Color(238, 112, 82));
        Address.setText("Address:");
        Address.setAlignmentY(0.0F);
        jPnlBody.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 308, 64, 19));

        LegalRepresentative.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        LegalRepresentative.setForeground(new java.awt.Color(238, 112, 82));
        LegalRepresentative.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LegalRepresentative.setText("<html>Legal Representative:</html>");
        LegalRepresentative.setAlignmentY(0.0F);
        LegalRepresentative.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPnlBody.add(LegalRepresentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 358, 115, 39));

        Phone.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Phone.setForeground(new java.awt.Color(238, 112, 82));
        Phone.setText("Phone:");
        Phone.setAlignmentY(0.0F);
        jPnlBody.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 131, 50, 19));

        Cellphone.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Cellphone.setForeground(new java.awt.Color(238, 112, 82));
        Cellphone.setText("Cellphone:");
        Cellphone.setAlignmentY(0.0F);
        jPnlBody.add(Cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 190, 80, 19));

        email.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(238, 112, 82));
        email.setText("e-mail:");
        email.setAlignmentY(0.0F);
        jPnlBody.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 246, 60, 19));

        Fax.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Fax.setForeground(new java.awt.Color(238, 112, 82));
        Fax.setText("Fax:");
        Fax.setAlignmentY(0.0F);
        jPnlBody.add(Fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 308, 30, 19));

        txtConcessionerName.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerName.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerName.setAlignmentX(0.0F);
        txtConcessionerName.setAlignmentY(0.0F);
        txtConcessionerName.setBorder(null);
        jPnlBody.add(txtConcessionerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 129, 194, 24));

        txtConcessionerRUC.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerRUC.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerRUC.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerRUC.setAlignmentX(0.0F);
        txtConcessionerRUC.setAlignmentY(0.0F);
        txtConcessionerRUC.setBorder(null);
        jPnlBody.add(txtConcessionerRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 188, 194, 24));

        txtConcessionerCity.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerCity.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerCity.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerCity.setAlignmentX(0.0F);
        txtConcessionerCity.setAlignmentY(0.0F);
        txtConcessionerCity.setBorder(null);
        jPnlBody.add(txtConcessionerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 244, 194, 24));

        txtConcessionerAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerAddress.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerAddress.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerAddress.setAlignmentX(0.0F);
        txtConcessionerAddress.setAlignmentY(0.0F);
        txtConcessionerAddress.setBorder(null);
        jPnlBody.add(txtConcessionerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 306, 172, 24));

        txtConcessionerLegalRepresentative.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerLegalRepresentative.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerLegalRepresentative.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerLegalRepresentative.setAlignmentX(0.0F);
        txtConcessionerLegalRepresentative.setAlignmentY(0.0F);
        txtConcessionerLegalRepresentative.setBorder(null);
        jPnlBody.add(txtConcessionerLegalRepresentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 365, 174, 24));

        txtConcessionerId.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerId.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerId.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerId.setAlignmentX(0.0F);
        txtConcessionerId.setAlignmentY(0.0F);
        txtConcessionerId.setBorder(null);
        jPnlBody.add(txtConcessionerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 77, 194, 24));

        txtConcessionerPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerPhone.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerPhone.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerPhone.setAlignmentX(0.0F);
        txtConcessionerPhone.setAlignmentY(0.0F);
        txtConcessionerPhone.setBorder(null);
        jPnlBody.add(txtConcessionerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 129, 194, 24));

        txtConcessionerCellphone.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerCellphone.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerCellphone.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerCellphone.setAlignmentX(0.0F);
        txtConcessionerCellphone.setAlignmentY(0.0F);
        txtConcessionerCellphone.setBorder(null);
        jPnlBody.add(txtConcessionerCellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 188, 194, 24));

        txtConcessionerEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerEmail.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerEmail.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerEmail.setAlignmentX(0.0F);
        txtConcessionerEmail.setAlignmentY(0.0F);
        txtConcessionerEmail.setBorder(null);
        jPnlBody.add(txtConcessionerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 244, 194, 24));

        txtConcessionerFax.setBackground(new java.awt.Color(255, 255, 255));
        txtConcessionerFax.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtConcessionerFax.setForeground(new java.awt.Color(36, 47, 65));
        txtConcessionerFax.setAlignmentX(0.0F);
        txtConcessionerFax.setAlignmentY(0.0F);
        txtConcessionerFax.setBorder(null);
        jPnlBody.add(txtConcessionerFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 306, 194, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jPnlBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 153, 194, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jPnlBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 213, 194, 1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel3.setAlignmentY(0.0F);
        jPnlBody.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 270, 194, 1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jPnlBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 330, 194, 1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel5.setAlignmentY(0.0F);
        jPnlBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 390, 194, 1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel6.setAlignmentY(0.0F);
        jPnlBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 102, 194, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel7.setAlignmentY(0.0F);
        jPnlBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 213, 194, 1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel8.setAlignmentY(0.0F);
        jPnlBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 270, 194, 1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel9.setAlignmentY(0.0F);
        jPnlBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 330, 194, 1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Piece Name Underline.png"))); // NOI18N
        jLabel10.setAlignmentY(0.0F);
        jPnlBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 153, 194, 1));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new Concessioner().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        if("".equals(txtConcessionerName.getText()) || "".equals(txtConcessionerRUC.getText()) || "".equals(txtConcessionerCity.getText())
            || "".equals(txtConcessionerAddress.getText()) || "".equals(txtConcessionerLegalRepresentative.getText())
            || "".equals(txtConcessionerPhone.getText()) || "".equals(txtConcessionerCellphone.getText()) || "".equals(txtConcessionerEmail.getText())
            || "".equals(txtConcessionerFax.getText()))
        {
            OkDialog dialog = new OkDialog(this, true);
            dialog.dialogText.setText("All fields are required!");
            dialog.setVisible(true);
        }
        else
        {
            int id;
            String ruc, name, address, city, legalRepresentative, phone, cellphone, mail, fax;
            id=Integer.parseInt(this.txtConcessionerId.getText());
            ruc=this.txtConcessionerRUC.getText();
            name=this.txtConcessionerName.getText();
            address=this.txtConcessionerAddress.getText();
            city=this.txtConcessionerCity.getText();
            legalRepresentative=this.txtConcessionerLegalRepresentative.getText();
            phone=this.txtConcessionerPhone.getText();
            cellphone=this.txtConcessionerCellphone.getText();
            mail=this.txtConcessionerEmail.getText();
            fax=this.txtConcessionerFax.getText();
            concessionerVO = new ConcessionerVO(id, ruc, name, address, city, legalRepresentative,  phone, cellphone, mail, fax);
            concessionerDAO.modifyConcessioner(concessionerVO);
            txtConcessionerId.setText("");
            txtConcessionerName.setText("");
            txtConcessionerRUC.setText("");
            txtConcessionerCity.setText("");
            txtConcessionerAddress.setText("");
            txtConcessionerLegalRepresentative.setText("");
            txtConcessionerPhone.setText("");
            txtConcessionerCellphone.setText("");
            txtConcessionerEmail.setText("");
            txtConcessionerFax.setText("");
        }
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        txtConcessionerId.setText("");
        txtConcessionerName.setText("");
        txtConcessionerRUC.setText("");
        txtConcessionerCity.setText("");
        txtConcessionerAddress.setText("");
        txtConcessionerLegalRepresentative.setText("");
        txtConcessionerPhone.setText("");
        txtConcessionerCellphone.setText("");
        txtConcessionerEmail.setText("");
        txtConcessionerFax.setText("");
    }//GEN-LAST:event_CancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyConcessionerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyConcessionerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CancelButton;
    private javax.swing.JLabel Cellphone;
    private javax.swing.JLabel City;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel Fax;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel LegalRepresentative;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel RUC;
    private javax.swing.JLabel SaveButton;
    private javax.swing.JLabel TitleView;
    private javax.swing.JLabel UnderlineTitleView;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JTextField txtConcessionerAddress;
    private javax.swing.JTextField txtConcessionerCellphone;
    private javax.swing.JTextField txtConcessionerCity;
    private javax.swing.JTextField txtConcessionerEmail;
    private javax.swing.JTextField txtConcessionerFax;
    private javax.swing.JTextField txtConcessionerId;
    private javax.swing.JTextField txtConcessionerLegalRepresentative;
    private javax.swing.JTextField txtConcessionerName;
    private javax.swing.JTextField txtConcessionerPhone;
    private javax.swing.JTextField txtConcessionerRUC;
    // End of variables declaration//GEN-END:variables
}
