/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ConcessionerDAO;
import Model.Order;
import Model.OrderDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Randy
 */
public class ModifyOrderForm extends javax.swing.JFrame {

    ConcessionerDAO concessionerDAO = new ConcessionerDAO();
    //ConcessionerVO concessionerVO;
    OrderDAO orderDao = new OrderDAO();
    Order order;
    int fila;
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");

    /**
     * Creates new form ViewConcessionerForm
     */
    public ModifyOrderForm() {

        initComponents();
        this.setLocationRelativeTo(null);
        RefreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        UnderlineTitleView = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrders = new rojerusan.RSTableMetro();
        btnCargar = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        txtIdOrder = new javax.swing.JTextField();
        txtOrderName = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jDateDeliveryOrder = new com.toedter.calendar.JDateChooser();
        jDateNowOrder = new com.toedter.calendar.JDateChooser();
        Id = new javax.swing.JLabel();
        txtMotoCode = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jsCantidad = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 870, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        UnderlineTitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title View Underline.png"))); // NOI18N
        UnderlineTitleView.setAlignmentY(0.0F);
        jPnlBody.add(UnderlineTitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 550, 20));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdOrder", "NameOrder", "FechaActual", "FechaEntrega", "IdMoto", "Cantidad"
            }
        ));
        tblOrders.setAlignmentX(0.0F);
        tblOrders.setAlignmentY(0.0F);
        tblOrders.setAltoHead(24);
        tblOrders.setColorBackgoundHead(new java.awt.Color(238, 112, 82));
        tblOrders.setColorBordeFilas(new java.awt.Color(112, 112, 112));
        tblOrders.setColorBordeHead(new java.awt.Color(112, 112, 112));
        tblOrders.setColorFilasBackgound1(new java.awt.Color(112, 112, 112));
        tblOrders.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblOrders.setColorFilasForeground1(new java.awt.Color(36, 47, 65));
        tblOrders.setColorFilasForeground2(new java.awt.Color(36, 47, 65));
        tblOrders.setColorSelBackgound(new java.awt.Color(238, 112, 82));
        tblOrders.setFillsViewportHeight(true);
        tblOrders.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblOrders.setFuenteFilas(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblOrders.setFuenteFilasSelect(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblOrders.setFuenteHead(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblOrders.setGridColor(new java.awt.Color(153, 153, 153));
        tblOrders.setGrosorBordeFilas(0);
        tblOrders.setMultipleSeleccion(false);
        tblOrders.setPreferredSize(new java.awt.Dimension(595, 350));
        tblOrders.setRowHeight(24);
        tblOrders.getTableHeader().setReorderingAllowed(false);
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrders);

        jPnlBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 430, 300));

        btnCargar.setText("Refrescar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPnlBody.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        Name.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(238, 112, 82));
        Name.setText("Id Order");
        Name.setAlignmentY(0.0F);
        jPnlBody.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 60, -1));

        txtIdOrder.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtIdOrder.setForeground(new java.awt.Color(36, 47, 65));
        txtIdOrder.setAlignmentX(0.0F);
        txtIdOrder.setAlignmentY(0.0F);
        jPnlBody.add(txtIdOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 60, 24));

        txtOrderName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtOrderName.setForeground(new java.awt.Color(36, 47, 65));
        txtOrderName.setAlignmentX(0.0F);
        txtOrderName.setAlignmentY(0.0F);
        jPnlBody.add(txtOrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 194, 30));

        Category.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Category.setForeground(new java.awt.Color(238, 112, 82));
        Category.setText("Oder´s Name:");
        Category.setAlignmentY(0.0F);
        jPnlBody.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 110, 19));

        Description.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Description.setForeground(new java.awt.Color(238, 112, 82));
        Description.setText("Delivery Date");
        Description.setAlignmentY(0.0F);
        jPnlBody.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 100, 19));
        jPnlBody.add(jDateDeliveryOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));
        jPnlBody.add(jDateNowOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        Id.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Id.setForeground(new java.awt.Color(238, 112, 82));
        Id.setText("Date");
        Id.setAlignmentY(0.0F);
        jPnlBody.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 60, 19));

        txtMotoCode.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtMotoCode.setForeground(new java.awt.Color(36, 47, 65));
        txtMotoCode.setAlignmentX(0.0F);
        txtMotoCode.setAlignmentY(0.0F);
        txtMotoCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotoCodeActionPerformed(evt);
            }
        });
        jPnlBody.add(txtMotoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 120, 30));

        Quantity.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Quantity.setForeground(new java.awt.Color(238, 112, 82));
        Quantity.setText("Motorcycle Code");
        Quantity.setAlignmentY(0.0F);
        jPnlBody.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 130, 19));

        Price.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Price.setForeground(new java.awt.Color(238, 112, 82));
        Price.setText("Amount");
        Price.setAlignmentY(0.0F);
        jPnlBody.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 70, 19));
        jPnlBody.add(jsCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));
        jPnlBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPnlBody.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 880, 530));

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if (dialog.getReturnStatus() == 1) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new OrderModule().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        RefreshTable();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtMotoCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotoCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotoCodeActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        // TODO add your handling code here:
        int select = tblOrders.getSelectedRow();
        if (select >= 0) {
            txtIdOrder.setText(tblOrders.getValueAt(select, 0).toString());
            txtOrderName.setText(tblOrders.getValueAt(select, 1).toString());
            
            Date fechanow;
            try {
                fechanow= dateFormat.parse(tblOrders.getValueAt(select, 2).toString());
                jDateNowOrder.setDate(fechanow);
            } catch (ParseException ex) {
                Logger.getLogger(ModifyOrderForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                fechanow= dateFormat.parse(tblOrders.getValueAt(select, 3).toString());
                jDateDeliveryOrder.setDate(fechanow);
            } catch (ParseException ex) {
                Logger.getLogger(ModifyOrderForm.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            txtMotoCode.setText(tblOrders.getValueAt(select, 4).toString());
            jsCantidad.setValue(tblOrders.getValueAt(select, 5));

            fila = select;
        }else{
            JOptionPane.showMessageDialog(null,"no selecciono fila");
        }


    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        if("".equals(txtIdOrder.getText()) || "".equals(txtOrderName.getText()) || "".equals(txtMotoCode.getText())
            || "".equals(jDateNowOrder.getDateFormatString()) || "".equals(jDateDeliveryOrder.getDateFormatString()))
        {
            OkDialog dialog = new OkDialog(this, true);
            dialog.dialogText.setText("All fields are required!");
            dialog.setVisible(true);
        }
        else
        {
            actualizar();
            //limpiar();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    public void actualizar(){
        String nameOrder = "";
        String fechaOrder = "";
        String fechaEntregaOrder = "";
        
        int  idOrder = 0;
        int  idMoto = 0;
        int cantidad = 0;
        idOrder= Integer.parseInt(txtIdOrder.getText());
        nameOrder= txtOrderName.getText();
       
        fechaOrder = dateFormat.format(jDateNowOrder.getDate());
        fechaEntregaOrder= dateFormat.format(jDateDeliveryOrder.getDate());
        idMoto= Integer.parseInt(txtMotoCode.getText());
        cantidad= (Integer)jsCantidad.getValue();
        Order order = new Order(idOrder,nameOrder,fechaOrder,fechaEntregaOrder,idMoto,cantidad);
        orderDao.modifyOrder(order);
          
    }
    private void RefreshTable() {
        ArrayList<Order> array = new ArrayList<Order>();

        array = orderDao.viewOrder();
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("IdOrder");
        model.addColumn("NameOrder");
        model.addColumn("FechaActual");
        model.addColumn("FechaEntrega");
        model.addColumn("IdMoto");
        model.addColumn("Cantidad");
        tblOrders.setModel(model);

        Object[] column = new Object[6];
        for (int i = 0; i < array.size(); i++) {
            column[0] = array.get(i).getIdOrder();
            column[1] = array.get(i).getNameOder();
            column[2] = array.get(i).getFechaActual();
            column[3] = array.get(i).getFechaEntrega();
            column[4] = array.get(i).getIdMoto();
            column[5] = array.get(i).getCantidad();

            model.addRow(column);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel UnderlineTitleView;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCargar;
    private com.toedter.calendar.JDateChooser jDateDeliveryOrder;
    private com.toedter.calendar.JDateChooser jDateNowOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jsCantidad;
    private rojerusan.RSTableMetro tblOrders;
    private javax.swing.JTextField txtIdOrder;
    private javax.swing.JTextField txtMotoCode;
    private javax.swing.JTextField txtOrderName;
    // End of variables declaration//GEN-END:variables

   


}
