/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ConcessionaireDAO;
import Model.ConcessionaireVO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melissa
 */
public class ShowConcessionaireForm extends javax.swing.JFrame {
    ConcessionaireVO objVO;
    ConcessionaireDAO objDAO=new ConcessionaireDAO();
    /**
     * Creates new form ShowConcessionaireForm
     */
    public ShowConcessionaireForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundBanner = new javax.swing.JLabel();
        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConcesionario = new javax.swing.JTable();
        btnDesplegar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        jTableConcesionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Ruc", "Nombre", "Representante"
            }
        ));
        jScrollPane1.setViewportView(jTableConcesionario);

        jPnlBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 440, 170));

        btnDesplegar.setText("Desplegar Concesionarios");
        btnDesplegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesplegarActionPerformed(evt);
            }
        });
        jPnlBody.add(btnDesplegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlWindowControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackgroundBanner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPnlWindowControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new ConcessionaireMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void btnDesplegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesplegarActionPerformed
          ArrayList<ConcessionaireVO> arr=new ArrayList<ConcessionaireVO>();
          
                arr=objDAO.mostrarConcesionario();
                DefaultTableModel modeloT=new DefaultTableModel();
                this.jTableConcesionario.setModel(modeloT);
                modeloT.addColumn("Id");
                modeloT.addColumn("Ruc");
                modeloT.addColumn("Nombre");
                modeloT.addColumn("Representante");
                Object[] columna=new Object[4];
                for(int i=0; i<arr.size(); i++){
                    columna[0]=arr.get(i).getIdConcesionario();
                    columna[1]=arr.get(i).getRucConcesionario();
                    columna[2]=arr.get(i).getNombreConcesionario();
                    columna[3]=arr.get(i).getRepresentanteConcesionario();

                    modeloT.addRow(columna);
                }
    }//GEN-LAST:event_btnDesplegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowConcessionaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowConcessionaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowConcessionaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowConcessionaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowConcessionaireForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JButton btnDesplegar;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConcesionario;
    // End of variables declaration//GEN-END:variables
}
