/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.PieceDAO;
import Model.TextPrompt;

/**
 *
 * @author Randy
 */
public class ViewPiecesForm extends javax.swing.JFrame {
    PieceDAO pieceDAO = new PieceDAO();
    String idPiece="";
    
    /**
     * Creates new form ViewPiecesForm
     */
    public ViewPiecesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        TextPrompt searchHint = new TextPrompt("Search", txtSearch);
        
        pieceDAO.viewPiece(tblPieces);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuItemEdit = new javax.swing.JMenuItem();
        MenuItemDelete = new javax.swing.JMenuItem();
        jPnlWindowControls = new javax.swing.JPanel();
        MinimiceControl = new javax.swing.JLabel();
        CloseControl = new javax.swing.JLabel();
        jPnlBody = new javax.swing.JPanel();
        BackControl = new javax.swing.JLabel();
        TitleView = new javax.swing.JLabel();
        UnderlineTitleView = new javax.swing.JLabel();
        SearchBy = new javax.swing.JLabel();
        SearchIcon = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPieces = new rojerusan.RSTableMetro();
        jPnlBanner = new javax.swing.JPanel();
        BackgroundBanner = new javax.swing.JLabel();

        MenuItemEdit.setBackground(new java.awt.Color(245, 245, 245));
        MenuItemEdit.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        MenuItemEdit.setForeground(new java.awt.Color(51, 51, 51));
        MenuItemEdit.setText("Edit");
        MenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuItemEdit);

        MenuItemDelete.setBackground(new java.awt.Color(245, 245, 245));
        MenuItemDelete.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        MenuItemDelete.setForeground(new java.awt.Color(51, 51, 51));
        MenuItemDelete.setText("Delete");
        MenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuItemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlWindowControls.setBackground(new java.awt.Color(255, 255, 255));
        jPnlWindowControls.setName(""); // NOI18N
        jPnlWindowControls.setPreferredSize(new java.awt.Dimension(755, 45));
        jPnlWindowControls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimiceControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 1, 20)); // NOI18N
        MinimiceControl.setForeground(new java.awt.Color(153, 153, 153));
        MinimiceControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Minimize Control.png"))); // NOI18N
        MinimiceControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimiceControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiceControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(MinimiceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 15, -1, 27));

        CloseControl.setFont(new java.awt.Font("Font Awesome 5 Free Regular", 0, 20)); // NOI18N
        CloseControl.setForeground(new java.awt.Color(153, 153, 153));
        CloseControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Control.png"))); // NOI18N
        CloseControl.setAlignmentY(0.0F);
        CloseControl.setAutoscrolls(true);
        CloseControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseControlMouseClicked(evt);
            }
        });
        jPnlWindowControls.add(CloseControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 15, -1, 27));

        getContentPane().add(jPnlWindowControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, 755, 45));

        jPnlBody.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Back Control.png"))); // NOI18N
        BackControl.setAlignmentY(0.0F);
        BackControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackControlMouseClicked(evt);
            }
        });
        jPnlBody.add(BackControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 32));

        TitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/View Pieces.png"))); // NOI18N
        TitleView.setAlignmentY(0.0F);
        jPnlBody.add(TitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 19, 220, 33));

        UnderlineTitleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Title View Underline.png"))); // NOI18N
        UnderlineTitleView.setAlignmentY(0.0F);
        jPnlBody.add(UnderlineTitleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 540, 3));

        SearchBy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Search By.png"))); // NOI18N
        SearchBy.setAlignmentY(0.0F);
        SearchBy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPnlBody.add(SearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 100, 139, 29));

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Search Button.png"))); // NOI18N
        SearchIcon.setAlignmentY(0.0F);
        SearchIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPnlBody.add(SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 105, 24, 24));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(36, 47, 65));
        txtSearch.setAlignmentX(0.0F);
        txtSearch.setAlignmentY(0.0F);
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        jPnlBody.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 105, 397, 24));

        tblPieces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0001", "Tire", "Tires", "Tires", "10", "79.00"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Category", "Description", "Quantity", "Providers"
            }
        ));
        tblPieces.setAlignmentX(0.0F);
        tblPieces.setAlignmentY(0.0F);
        tblPieces.setAltoHead(24);
        tblPieces.setColorBackgoundHead(new java.awt.Color(238, 112, 82));
        tblPieces.setColorBordeFilas(new java.awt.Color(112, 112, 112));
        tblPieces.setColorBordeHead(new java.awt.Color(112, 112, 112));
        tblPieces.setColorFilasBackgound1(new java.awt.Color(112, 112, 112));
        tblPieces.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblPieces.setColorFilasForeground1(new java.awt.Color(36, 47, 65));
        tblPieces.setColorFilasForeground2(new java.awt.Color(36, 47, 65));
        tblPieces.setColorSelBackgound(new java.awt.Color(238, 112, 82));
        tblPieces.setComponentPopupMenu(jPopupMenu1);
        tblPieces.setFillsViewportHeight(true);
        tblPieces.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblPieces.setFuenteFilas(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblPieces.setFuenteFilasSelect(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblPieces.setFuenteHead(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblPieces.setGridColor(new java.awt.Color(153, 153, 153));
        tblPieces.setGrosorBordeFilas(0);
        tblPieces.setMultipleSeleccion(false);
        tblPieces.setPreferredSize(new java.awt.Dimension(595, 350));
        tblPieces.setRowHeight(24);
        tblPieces.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblPieces);
        if (tblPieces.getColumnModel().getColumnCount() > 0) {
            tblPieces.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jPnlBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 560, 360));

        getContentPane().add(jPnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 45, 755, 530));

        jPnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBanner.setName("jPnlBanner"); // NOI18N
        jPnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BackgroundBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Banner1.png"))); // NOI18N
        BackgroundBanner.setAlignmentY(0.0F);
        BackgroundBanner.setPreferredSize(new java.awt.Dimension(296, 577));
        jPnlBanner.add(BackgroundBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 575));

        getContentPane().add(jPnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimiceControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiceControlMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_MinimiceControlMouseClicked

    private void CloseControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseControlMouseClicked
        ConfirmDialog dialog = new ConfirmDialog(this, true);
        dialog.dialogText.setText("Do you want to logout?");
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==1)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_CloseControlMouseClicked

    private void BackControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackControlMouseClicked
        new Warehouse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackControlMouseClicked

    private void MenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditActionPerformed
        int row = tblPieces.getSelectedRow();
        if(row>=0)
        {
            idPiece = tblPieces.getValueAt(row, 0).toString();
            //Buscar datos en la tabla segun el id para cargarlos en el otro formulario
            new EditPieceForm(idPiece).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_MenuItemEditActionPerformed

    private void MenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteActionPerformed
        int row = tblPieces.getSelectedRow();
        if(row>=0)
        {
            idPiece = tblPieces.getValueAt(row, 0).toString();
            ConfirmDialog dialog = new ConfirmDialog(this, true);
            dialog.dialogText.setText("Are you sure to delete this item?");
            dialog.setVisible(true);
            if(dialog.getReturnStatus()==1)
            {
                pieceDAO.deletePiece(Integer.parseInt(idPiece));
                //Sentencia SQL para eliminar dato de la tabla
                //Actualizar Tabla
                new Warehouse().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_MenuItemDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPiecesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPiecesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPiecesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPiecesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPiecesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackControl;
    private javax.swing.JLabel BackgroundBanner;
    private javax.swing.JLabel CloseControl;
    private javax.swing.JMenuItem MenuItemDelete;
    private javax.swing.JMenuItem MenuItemEdit;
    private javax.swing.JLabel MinimiceControl;
    private javax.swing.JLabel SearchBy;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JLabel TitleView;
    private javax.swing.JLabel UnderlineTitleView;
    private javax.swing.JPanel jPnlBanner;
    private javax.swing.JPanel jPnlBody;
    private javax.swing.JPanel jPnlWindowControls;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSTableMetro tblPieces;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
